### ISSUE TITLE
Format entire project

### ISSUE THREAD

**Issue by robinsonjohn** [WalrusSoup/Tailwind-Formatter#55]
My apologies if I missed it, but I was wondering if there was a way to format the entire project- perhaps based off of the project's `tailwind.config.js` file `content` array.

Currently, the only way I know of to use this plugin is to run `Code > Run Tailwind Formatter` for each individual page. 

Thank you for the great resource!

**Comment by usernotnull** [comment]
I came to raise the exact same issue! Definitely needed.

**Comment by cmdNiels** [comment]
Any updated on this feature?

**Comment by WalrusSoup** [comment]
Sorry, i've had an incredibly busy Q4 so I got side tracked. I will get this going again and shipped soon! :)

**Comment by WalrusSoup** [comment]
This is done, pending acceptance into the Jetbrains store.
