### ISSUE TITLE
Does not work when encounters variants classes

### ISSUE THREAD

**Issue by dc-p8** [WalrusSoup/Tailwind-Formatter#62]
`[.peer:checked~&>.material-icons]:opacity-100` is a perfect valid tailwind class (see [arbitrary variants](https://github.com/tailwindlabs/tailwindcss/pull/8299) ), but when the plugin encounters this kind of classes, it refuses to format the whole element. Removing this class allow the plugin to format the element's classes.

No log lines appear exept the default one :
2023-02-07 11:30:53,345 [127201544]   INFO - #TailwindUtility - Loading default class order

**Comment by WalrusSoup** [comment]
Can you make sure you're on the latest version (2.0.1) in your IDE?

Also, can you give me a sample file that it's failing to work with? When testing against the latest release, it appears to move the variant to the beginning of the main variants area. Per play.tailwindcss.com - it should be in the back. I can definitely fix this, but I am curious to check in on the fact it stops formatting entirely first.

```txt
Expected :flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0 [.peer:checked~&>.material-icons]:opacity-100
Actual   :flex min-h-full items-end justify-center p-4 text-center [.peer:checked~&>.material-icons]:opacity-100 sm:items-center sm:p-0
```

**Comment by WalrusSoup** [comment]
Could be related to https://github.com/WalrusSoup/Tailwind-Formatter/pull/63 actually. Let me know if you have issues after that goes out.

**Comment by WalrusSoup** [comment]
I have confirmed with @tance77 that the new release for the jetbrains store does work. The final part of the question is, then:

Should arbitrary variants be sorted to the very back of the variants list? I suppose it would make sense to do it that way. I'll see if i can get that patched in this weekend.

**Comment by dc-p8** [comment]
I confirm that the issue is still present in v2.0.2.
This file 
`<div class="sm:p-0 flex min-h-full items-end justify-center p-4 text-center sm:items-center [.peer:checked~&>.material-icons]:opacity-100"></div>`
can't be formatted. Removing the last class and it works. Same behaviour in @apply

**Comment by WalrusSoup** [comment]
I ended up rewriting the variant handling here:  https://github.com/WalrusSoup/Tailwind-Formatter/pull/64

This file shows the output and the test is passing:

https://github.com/WalrusSoup/Tailwind-Formatter/blob/982af1a8c7c4479f956106be71f876c54b3ce91f/src/test/testData/parser/arbitrary-variant-expected.vue

and the tests pass in the GH action.

The last thing I'm going to do is bring in more complicated examples. I'll make some over in play.tailwindcss.com and shuffle the classes around and make sure its all 100% before I ship it out. I cant possibly guess every configuration people will use, but I'm going to really try to get most of them.

**Comment by WalrusSoup** [comment]
assuming we gucci - gonna close this.
