### ISSUE TITLE
Tailwind formatter orders classes differently than Prettier

### ISSUE THREAD

**Issue by jashaj** [WalrusSoup/Tailwind-Formatter#78]
Tailwind classes are ordered differently in Vue files when I format with this plugin compared to running prettier. What's causing the difference?

Tailwind formatter:

```html
<div class="mt-8 mb-2 flex items-center">
  <button class="my-2 w-full p-2 btn btn-primary" @click="router.back()">Cancel</button>
</div>
```

Prettier:

```html
<div class="mb-2 mt-8 flex items-center">
  <button class="btn btn-primary my-2 w-full p-2" @click="router.back()">Cancel</button>
</div>
```

Versions:

- prettier: 3.0.3
- prettier-plugin-tailwindcss: 0.5.6
- tailwindcss: 3.3.3
- Tailwind Formatter: 2.0.8
- WebStorm: 2023.2.3

.prettierrc.json:

```json
{
  "$schema": "https://json.schemastore.org/prettierrc",
  "printWidth": 120,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "arrowParens": "avoid",
  "bracketSameLine": true,
  "plugins": ["prettier-plugin-tailwindcss"]
}
```

Moving the contents of `.prettier.json` to the `package.json` did not fix the issue.

**Comment by WalrusSoup** [comment]
Prettier has better access to class order under the hood. it [natively calls tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/src/sorting.js#L84C17-L84C30), and can access [generate rules](https://github.com/tailwindlabs/tailwindcss/blob/a091db5df4651fde85fcf917b11fdaa210b79623/src/lib/generateRules.js#L885) which has access to the *actual* rules. As far as im understanding, these come from the compiler that has access to the classes which are actually used. Currently, this one is guessing the order that they appear in, so it's not as narrowed down unfortunately.

Ultimately, though, i think that we opt to put the custom ones in the back and they opt to push it into the front.

I'd love if we could call the tailwindcss executable and get the generated rules as JSON via the CLI or something, but I'd have to add that to the tailwind library and im super unfamiliar with how it works structurally.

**Comment by jashaj** [comment]
Thanks for the explanation and sorry for the late response. I'll close this issue as it seems to be a huge effort while prettier can also format my code on save.
