### ISSUE TITLE
Support for build 242.*

### ISSUE THREAD

**Issue by chrisnoden** [WalrusSoup/Tailwind-Formatter#87]
With the release of the 242 (2024) builds of the JetBrains IDEs, the Tailwind Formatter plugin no longer works.

Please could you update to support the new builds?

**Comment by mikesnoeren** [comment]
Genuine question: I'm curious why this plugin seems to become outdated so frequently. I haven't experienced this with other plugins. Is it due to a lack of maintenance, or is there something inherently challenging about how it's built?

I also noticed someone made a [pull request](https://github.com/WalrusSoup/Tailwind-Formatter/pull/88) that supposedly fixes this issue. Is there any reason it hasn't been accepted?

**Comment by tance77** [comment]
> Genuine question: I'm curious why this plugin seems to become outdated so frequently. I haven't experienced this with other plugins. Is it due to a lack of maintenance, or is there something inherently challenging about how it's built?
> 
> I also noticed someone made a [pull request](https://github.com/WalrusSoup/Tailwind-Formatter/pull/88) that supposedly fixes this issue. Is there any reason it hasn't been accepted?

We are just busy and Jetbrains is always pushing new updates. 

@chrisnoden 
I'll remind him to update this.  It's really just a version bump.

**Comment by tance77** [comment]
@chrisnoden  Should be up to date now.

**Comment by chrisnoden** [comment]
Many thanks @tance77 - it does seem to be working, although it does generate a deprecation warning:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.walrussoup.tailwindformatternext.actions.FormatFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.myoutdesk.tailwind_formatter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
